# Normalize cmdliner --help=plain output across OCaml versions.
#
# Older OCaml runtimes detect a narrower default margin for [Format],
# which causes cmdliner to wrap the SYNOPSIS line onto a continuation
# line. OCaml 5.4 keeps it on a single line. We unwrap the continuation
# so cram traces are stable across versions.

/^SYNOPSIS$/ {
  print
  in_syn = 1
  held = ""
  next
}

in_syn {
  if ($0 ~ /^[[:space:]]*$/) {
    if (held != "") print held
    print
    in_syn = 0
    held = ""
    next
  }
  if (held == "") {
    held = $0
  } else {
    cont = $0
    sub(/^[[:space:]]+/, " ", cont)
    held = held cont
  }
  next
}

{ print }

END { if (held != "") print held }

# Background.
#
# OCaml 5.4 added an [out_width] field to [Format]'s output functions,
# defaulting to [Format.utf_8_scalar_width] — the formatter now measures
# strings in Unicode scalar values rather than bytes. Pre-5.4 counted
# bytes. The [OPTION]… token includes [U+2026] (3 bytes, 1 scalar), so
# at the default margin of 78 the cmdliner SYNOPSIS line is right at the
# boundary: pre-5.4 it tips over (byte-count) and wraps; on 5.4 it fits
# on a single line (scalar-count).
#
# Cmdliner does not expose any knob for the margin or for [out_width],
# and OCaml's [Format] has no env-var equivalent either. The cleanest
# programmatic fix would be to set [out_width = Format.ascii_width] in
# the test binary, but [ascii_width] / [out_width] only exist on 5.4+,
# which would require version-conditional compilation.
#
# Policy.
#
# For now we support both OCaml 5.3 and 5.4 in the cram tests via this
# filter, applied only to the cmdliner [--help=plain] invocations whose
# SYNOPSIS lands on the wrapping boundary. We make no strong guarantee
# that this will continue: once we drop pre-5.4 support, this filter
# can be deleted and the affected tests can capture the post-5.4 output
# directly.
#
# Acknowledgements.
#
# This script and the explanatory comments above were AI-generated by
# Claude Opus 4.7 (model id [claude-opus-4-7]).
