#!/bin/bash
# SPDX-FileCopyrightText: 2026 Mathieu Barbin <opensource@mbarbin.org>
# SPDX-License-Identifier: MIT

# Test runner for run.sh. Runs all OS/version/format combinations
# and outputs results for expect testing via dune promotion.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN_SH="$SCRIPT_DIR/run.sh"

echo "; Generated by test.sh - do not edit"
echo ""

OS_LIST="macos-latest ubuntu-latest windows-latest"
VERSION_LIST="4.14 5.2 5.3"
FORMAT_LIST="dune opam"

for os in $OS_LIST; do
  for version in $VERSION_LIST; do
    for format in $FORMAT_LIST; do
      echo "$ run.sh $os $version $format"
      "$RUN_SH" "$os" "$version" "$format"
      echo ""
    done
  done
done

# Test that versions with .x suffix also work (for backward compatibility)
echo "# Versions with .x suffix"
echo ""
for version in $VERSION_LIST; do
  echo "$ run.sh ubuntu-latest ${version}.x dune"
  "$RUN_SH" ubuntu-latest "${version}.x" dune
  echo ""
done

# Error cases are tested in run.t (cram test)
