name: CRs Workflows

on:
  pull_request:
    branches:
      - "**" # This will match pull requests targeting any branch

permissions:
  contents: read
  pull-requests: write

jobs:
  crs-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install crs
        uses: mbarbin/crs-actions/setup-crs@9eed5c55f144e4e3adbb9a871dcae6d135c37256 # v1.0.0-alpha.11
        with:
          crs-version: 0.0.20260307
          crs-digest: sha256:5097e709386d8d41351a87f86c8ad374db72aabe4ddc2a8ff2d58faebb1b889f

      - name: Summarize CRs in PR
        uses: mbarbin/crs-actions/summarize-crs-in-pr@9eed5c55f144e4e3adbb9a871dcae6d135c37256 # v1.0.0-alpha.11
        with:
          crs-config: .github/crs-config.json
