name: Dunolint Workflows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**" # This will match pull requests targeting any branch

permissions:
  contents: read

jobs:
  dunolint-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install dunolint
        uses: mbarbin/dunolint-actions/setup-dunolint@a29eea82e86ed2a5cc1ee25e15dc615d77ac4b4f # v1.0.0-alpha.5
        with:
          dunolint-version: 0.0.20260306
          dunolint-digest: sha256:b83c07dd352cd4bec36b872ac593f299972710baff70a62e7a4650e80d2460d4

      - name: Lint Check
        uses: mbarbin/dunolint-actions/lint-check@a29eea82e86ed2a5cc1ee25e15dc615d77ac4b4f # v1.0.0-alpha.5
